build:
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run
  image: default-bionic
  environment:
    php:
      version: "7.2"
filter:
  excluded_paths:
  - 'tests/*'
