---
version: "3.0"
services:
  app72:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
    environment:
        PHP_IDE_CONFIG: 'serverName=icanboogie-prototype'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
  app82:
    build:
      context: .
      args:
        PHP_VERSION: 8.2
    environment:
        PHP_IDE_CONFIG: 'serverName=icanboogie-prototype'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
